FROM centos:

#Steps

# Build MPICH

# Download OpenFOAM source

# Download Third-Party source

# Install dependencies

# Set up OpenFOAM bashrc and env.

# Build Third-Party

# Build OpenFOAM

# Build ParaView
